version: "3.8"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  #####################
  ### Nginx Proxy
  #####################
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=1170167
      - POSTGRES_PASSWORD=1170167
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
